### PR TITLE
Fix undefined behaviour in parseSAMpaired

### LINKED ISSUE #19: Set all output parameters in parse_sam_line function
The function `parse_sam_line`  takes arguments by reference and the callsites expect that these variables are set by the function. Depending on the contents of the SAM file, this may not be the case. For instance, `a_score` is not necessarily set.

### PR DESCRIPTION
**Pull request by m-8k**
- in case of missing "AS" in SAM file `a_score` was not set
- return NaN and skip check in this case

### CODE REVIEW

File: PredictHaplo_externAlign.cpp [hunk 1]
```diff
@@ -276,9 +277,10 @@ void parseSAMpaired(string al, double max_gap_fraction,
       if (seq_b.size() > min_length && seq_b_pairs.size() > min_length &&
```
Comment (kpj) [inline PredictHaplo_externAlign.cpp:277]: Do I understand it correctly that previously this condition would be false if `a_score` wasn't set which would lead to all reads being skipped?
In the new implementation reads will still be included when `a_score` is NaN?

Comment (m-8k) [reply PredictHaplo_externAlign.cpp:277]: In my understanding the previous behavior was undefined (comparison with a variable that had not been assigned a value). In practice, `a_score` was often equal to, or very close to, zero. This meant that reads would be rejected if `min_align_score_fraction` was non-negative/positive.

That's correct, the new implementation uses reads without an `a_score`. Is this acceptable?

Comment (kpj) [reply PredictHaplo_externAlign.cpp:277]: Yes, I think it is fine for now!
